=== tornyak/picsms/res/xml/picsms.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="pictureBook">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="category" maxOccurs="unbounded"/>
        <xs:element ref="picture" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="language" type="xs:language" default="EN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="category">
    <xs:complexType>
      <xs:sequence>
      	<xs:element name="text" type="xs:string"/>
        <xs:element ref="picture" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="image" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="picture">
    <xs:complexType>
      <xs:sequence>
		<xs:element name="text" type="xs:string" maxOccurs="1"/>
		<xs:element name="action" type="xs:string" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="type" type="xs:string"/>
      <xs:attribute name="image" type="xs:string"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== tornyak/picsms/res/xml/picture_book.xml
<?xml version="1.0" encoding="UTF-8"?>

<pictureBook name="default"
             language="HR"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="picsms.xsd">
  
	<category name="activities"
               image="@drawable/aktivnosti">       
    	<text>aktivnosti</text>

    	<picture name="throw"
         	     type="word"
         	     image="@drawable/aktivnosti_baci">
        	<text>baci</text>
    	</picture>    
    
    <picture name="reads"
             type="word"             
             image="@drawable/aktivnosti_cita">
      <text>čita</text>
		</picture>
    
           
    <picture name="draws"   
             type="word"
             image="@drawable/aktivnosti_crta">
      	<text>crta</text>
	</picture>
    
    
<!--     <picture name="give"
             type="word"
             image="@drawable/aktivnosti_daj">
      <text>daj</text>
		</picture> -->
    
    
    <picture name="lift"
             type="word"
             image="@drawable/aktivnosti_digni">
        <text>podigni</text>
			</picture>
    
    
<!--     <picture name="come"
             type="word"
             image="@drawable/aktivnosti_dodji">
        <text>dođi</text>
			</picture> -->
    
    
    <picture name="watching_tv"
             type="word"            
             image="@drawable/aktivnosti_gledati_tv">
    	<text>gledati TV</text>
			</picture>
    

    <picture name="eats"
             type="word"
             image="@drawable/aktivnosti_jede">
             <text>jede</text>
			</picture>
    
       
    <picture name="poo"
             type="word"
             image="@drawable/aktivnosti_kaka">
             <text>kaka</text>
			</picture>
    
    
    <picture name="lies"
             type="word"
             image="@drawable/aktivnosti_lezi">
             <text>leži</text>
			</picture>
    
    
    <picture name="catch"
             type="word"
             image="@drawable/aktivnosti_lovi">
             <text>lovi</text>
			</picture>
    
    
    <picture name="carries"
             type="word"
             image="@drawable/aktivnosti_nosi">
             <text>nosi</text>
			</picture>
    
    
    <picture name="falls"
             type="word"
             image="@drawable/aktivnosti_pada">
             <text>pada</text>
			</picture>
    
    
    <picture name="climbs"
             type="word"
             image="@drawable/aktivnosti_penje_se">
             <text>penje se</text>
			</picture>
    

    <picture name="washes"
             type="word"
             image="@drawable/aktivnosti_pere">
             <text>prati</text>
			</picture>
    
    
    <picture name="baths"
             type="word"
             image="@drawable/aktivnosti_pere_4">
             <text>prati glavu</text>
			</picture>
    

    <picture name="washes_hands"
             type="word"
             image="@drawable/aktivnosti_pere_ruke">
             <text>prati ruke</text>
			</picture>
    
    
    <picture name="drinks"
             type="word"
             image="@drawable/aktivnosti_piti">
             <text>piti</text>
			</picture>
    
    
    <picture name="dances"
             type="word"
             image="@drawable/aktivnosti_plese">
             <text>pleše</text>
			</picture>
    
    
    <picture name="swims"
             type="word"
             image="@drawable/aktivnosti_pliva">
             <text>pliva</text>
			</picture>
       
    
    <picture name="blows"
             type="word"
             image="@drawable/aktivnosti_puse">
             <text>puše</text>
			</picture>
    
    
    <picture name="cuts"
             type="word"
             image="@drawable/aktivnosti_reze">
             <text>reže</text>
			</picture>
    

    <picture name="sit"
             type="word"
             image="@drawable/aktivnosti_sjedni">
             <text>sjedni</text>
			</picture>
    
    
    <picture name="sleeps"
             type="word"
             image="@drawable/aktivnosti_spava_2">
             <text>spava</text>
			</picture>
    
    
    <picture name="runs"
             type="word"
             image="@drawable/aktivnosti_trci">
             <text>trči</text>
			</picture>
    
    
    <picture name="kick"
             type="word"
             image="@drawable/aktivnosti_udari_nogom">
             <text>udari nogom</text>
			</picture>
          
  </category>
  
 <category name="tools"
     image="@drawable/alat">
    <text>alat</text>
    
    <picture name="nail"
             type="word"
             image="@drawable/alat_cavao">
             <text>cavao</text>
    </picture>
    
    <picture name="hammer"
             type="word"
             image="@drawable/alat_cekic">
             <text>cekic</text>
    </picture>
    
    <picture name="pliers"
             type="word"
             image="@drawable/alat_kljesta">
             <text>klijesta</text>
    </picture>
    
    <picture name="ladder"
             type="word"
             image="@drawable/alat_lojtre">
             <text>lojtre</text>
    </picture>
    
    <picture name="screwdriver"
             type="word"
             image="@drawable/alat_odvijac">
             <text>odvijac</text>
    </picture>
    
    <picture name="saw"
             type="word"
             image="@drawable/alat_pila">
             <text>pila</text>
    </picture>
    
    <picture name="to_saw"
             type="word"
             image="@drawable/alat_piliti">
             <text>piliti</text>
    </picture>
    
    <picture name="axe"
             type="word"
             image="@drawable/alat_sjekira">
             <text>sjekira</text>
    </picture>
    
    <picture name="scissors"
             type="word"
             image="@drawable/alat_skare">
             <text>skare</text>
    </picture>
    
    <picture name="thread"
             type="word"
             image="@drawable/alat_spaga">
             <text>spaga</text>
    </picture>
    
    <picture name="to_nail"
             type="word"
             image="@drawable/alat_zabiti_cavao">
             <text>zabiti cavao</text>
    </picture>
    
     
 </category>

  <category name="body"
           image="@drawable/tijelo">
           <text>tijelo</text>
    

    <picture name="hair"
             type="word"
             image="@drawable/tijelo_kosa">
             <text>kosa</text>
			</picture>
    


    <picture name="nose"
             type="word"
             image="@drawable/tijelo_nos">
             <text>nos</text>
			</picture>
    

    <picture name="eyes"
             type="word"
             image="@drawable/tijelo_oci">
             <text>oči</text>
			</picture>
    

    <picture name="eye"
             type="word"
             image="@drawable/tijelo_oko">
             <text>oko</text>
			</picture>
    

    <picture name="hand"
             type="word"
             image="@drawable/tijelo_ruka">
             <text>ruka</text>
			</picture>
    
    
    <picture name="ear"
             type="word"
             image="@drawable/tijelo_uho">
             <text>uho</text>
			</picture>
    

    <picture name="mouth"
             type="word"
             image="@drawable/tijelo_usta">
             <text>usta</text>
			</picture>
            
  </category>
 
  <category name="food"
             image="@drawable/hrana">
             <text>hrana</text>

    <picture name="chips"
             type="word"
             image="@drawable/hrana_cips">
             <text>čips</text>
			</picture>
    

    <picture name="chocolate"
             type="word"
             image="@drawable/hrana_cokolada">
             <text>čokolada</text>
			</picture>
    
    
    <picture name="breakfast"
             type="word"
             image="@drawable/hrana_dorucak">
             <text>doručak</text>
			</picture>
    

    <picture name="popcorns"
             type="word"
             image="@drawable/hrana_kokice">
             <text>kokice</text>
			</picture>
    

    <picture name="bread"
             type="word"
             image="@drawable/hrana_kruh">
             <text>kruh</text>
			</picture>
    

    <picture name="muffin"
             type="word"
             image="@drawable/hrana_mufin">
             <text>muffin</text>
			</picture>
    

    <picture name="pretzel"
             type="word"
             image="@drawable/hrana_perec">
             <text>perec</text>
			</picture>
    

    <picture name="pizza"
             type="word"
             image="@drawable/hrana_pizza">
             <text>pizza</text>
			</picture>
    

    <picture name="french_fries"
             type="word"
             image="@drawable/hrana_pomfrit">
             <text>pomfit</text>
			</picture>
    

    <picture name="lunch"
             type="word"
             image="@drawable/hrana_rucak">
             <text>ručak</text>
			</picture>
    

    <picture name="cheese"
             type="word"
             image="@drawable/hrana_sir">
             <text>sir</text>
			</picture>
    

    <picture name="ice_cream"
             type="word"
             image="@drawable/hrana_sladoled">
             <text>sladoled</text>
			</picture>
    

    <picture name="dough"
             type="word"
             image="@drawable/hrana_tijesto">
             <text>tijesto</text>
			</picture>
    

    <picture name="cake"
             type="word"
             image="@drawable/hrana_torta">
             <text>torta</text>
			</picture>
    

    <picture name="water"
             type="word"
             image="@drawable/hrana_voda">
             <text>voda</text>
			</picture>
    
         
  </category>
  
  <category name="animals"
             image="@drawable/zivotinje">
             <text>životinje</text>
           
    <picture name="horse"
             type="word"
             image="@drawable/zivotinje_konj">
             <text>konj</text>
			</picture>
    

    <picture name="cow"
             type="word"
